### ISSUE TITLE
Irreführende Beschreibung der Cron Einträge in der Readme

### ISSUE THREAD

**Issue by rkorn86** [RundesBalli/pr0gramm-Spendenraid#1]
In deiner Readme schreibst du von "alle 5" beim Cron, schreibst aber `5,10,20,25,35,40,50,55` da fehlt die volle Stunde, sonst sinds zwischen 55 und 5 ganze 10 Minuten! Mach doch einfach `*/5`, so wie die Zeile drüber mit der viertel Stunde. 

Gruß und Krebs ist scheiße!

**Comment by RundesBalli** [comment]
Hi,

die erste Zeile `*/15` löst um 0, 15, 30 und 45 den großen Crawl aus und um `5,10,20,25,35,40,50,55` den kleinen Crawl.
Daran ist alles korrekt. Also `*/15` löst auch bei 0 aus.

Hier ein Screenshot aus der aktuellen Auswertung:
![grafik](https://user-images.githubusercontent.com/46271553/112753765-531cbe80-8fd9-11eb-8824-0259813602d4.png)

Danke aber für die Meldung und vielen Dank für die Aufmerksamkeit.

Viele Grüße
Balli

**Comment by rkorn86** [comment]
Du verstehst mich falsch. In dem Text der readme steht "und alle 5 Minuten in einem kleinen Scan". Das stimmt nicht mit deinem Cron überein.
